{% set version = "2.3.0" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: 81fae7e3c086ebc4b11933e731933f66181a45ca8b0adc10ba04aaa5a69cb949

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - qtpy >=1.3,<2.0
    - pyqt
  run:
    - python >=2.7
    - qtpy >=1.3,<2.0
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PierreRaybaut/guidata
  license: CECILL-2.0
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt Python binding module PyQt4, guidata is a Python library
    generating graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for PyQt4.
  doc_url: https://pythonhosted.org/guidata/
  dev_url: https://github.com/PierreRaybaut/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
