{% set name = "guidata" %}
{% set version = "3.0.0" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: 8e49ca6f8db14c6a5c2a12f9877e68e013cde8ab33053a98fd8002190e5e985b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - qtpy >=1.3
    - pyqt
  run:
    - python >=3.6
    - qtpy >=1.3
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Codra-Ingenierie-Informatique/guidata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt library, guidata is a Python library generating
    graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for Qt
    (PyQt5, PySide2, PyQt6, PySide6).
  doc_url: https://guidata.readthedocs.io
  dev_url: https://github.com/Codra-Ingenierie-Informatique/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
