{% set name = "guidata" %}
{% set version = "3.0.4" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0eae878c64cf9338174e48af59c1399143b3ad1f5187dc5a30755be18a16e19c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - h5py >=3.0
    - numpy >=1.21
    - qtpy >=1.9
    - requests
    - tomli
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Codra-Ingenierie-Informatique/guidata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt library, guidata is a Python library generating
    graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for Qt
    (PyQt5, PySide2, PyQt6, PySide6).
  doc_url: https://guidata.readthedocs.io
  dev_url: https://github.com/Codra-Ingenierie-Informatique/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
