{% set version = "3.0.0" %}

package:
  name: guidata
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guidata/archive/v{{ version }}.tar.gz
  sha256: 8e49ca6f8db14c6a5c2a12f9877e68e013cde8ab33053a98fd8002190e5e985b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - qtpy >=1.3
    - pyqt
  run:
    - python >=3.6
    - qtpy >=1.3
    - pyqt

test:
  imports:
    - guidata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PierreRaybaut/guidata
  license: CECILL-2.0
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on the Qt Python binding module PyQt4, guidata is a Python library
    generating graphical user interfaces for easy dataset editing and display.
    It also provides helpers and application development tools for PyQt4.
  doc_url: https://pythonhosted.org/guidata/
  dev_url: https://github.com/PierreRaybaut/guidata

extra:
  recipe-maintainers:
    - marcelotrevisani
    - denivyruck
    - beenje
