travis:
  secure:
    BINSTAR_TOKEN: ETsS/UT1xFV3jqF+f2B3n3oczw0p8ySUSsQRSwPhmpV0yqOV+e2Al/cQHijWI9bjzrn9yDZmOciiVxr7G0KL2HYAgpm9hcLVyR0Jb+aFEoJB/6Akkb7fmgH9pguZGkJT/QV91Fn5sG3JWpvNc3CuxUlVwpyfkiy4Ok8s4cxtt2cMXc543B2lYQgEmZBMioYpdXeAgg3M98IWT0PbrqDdCp8Etkl1QOCXc0H4MI/scKNKLkXOX91Jr41SIwZBaVlHmY91fco+STJpbg9F/ImGcw6ZAEOjWxGJZKlBgGccqqNNgHGuKp76ejL3QXmUh5S3nZv/ZnB+TNaAbfhMolSU2nqtwoUFegjKVr10Ek+WlYYmHidPZ/b6/E/8P1GxOthcUV6qArr9OFlpN1h66FEAZFpnjMGuzv799tcc7X+JgzcXXSRhiPwhMwja8kG9VLGy7n5PvED9qVMGuVwfK9qa0/5lL/F9fWP+JBK8tL7xHc2IWC2ZK/Qfp7TcYXO4IvkTOlAyArOBCHAKa+J3PxwDB/6NlBrpjV5zD8OIrXuj9xEz9miiJ3wi1W71g1ht5nkTNMYQ91agjVIm1gPWs8em+486NMF95aAVkPXaTE8O3BWCvZMreRDfdki8S66x+zkaJn2NEJsDcaKB+HNumIr87l+vCqqnVOdPUF/3+QD3FqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
