travis:
  secure:
    BINSTAR_TOKEN: 6Sw3s6KYy6hqam4mkra8wpVP/CYgYldaooM4DbzH0Ug51JMvqiY22Y9GPIQAGTDx8SxPIWgGU4NnhYMogSQkzcluPafAGgyGQMDZT9mt7AxmRkxk8SISvtIzbdG1NablbyY1Ed1b1QM5YDZAhB1tlWknt1EwB4wGqRl9WRLe+xS1bmbCAponArBqnPAwJX60WKlyExNiSoMWGSGS8uBiQSYr1gLp7f5EyqfpWK0cWBZ3PLch+uRDEXxUYN7xYn7vnXZcHIb6DeMctX/GX+qW/xO5ZX4QpYXcPqQJaKJP3/XtvpMBgsnCHPluyVfXPQFdklBzepuyA/RQ0RYFuDPVQAQYsbw72Ku8YQBCwOfbVhgv5vuV7AVZSHE0+2Xi2TY4QJkuTvbhDK+ZB/AOqBSPwXAhRVcs0y8SHFuyDWnpDaUkZdU1+x7Jb70NHrEPkzzEan9vjWTHCN8oT+z0zDm0oO8LbyviRySJAV9nzX1zOQYyR3ORzKPeXAg1HjVEjwEKbk5pkXeGweY+vkQXTdqLlN8f5R/xBaJ+e0mJmbEULaal4Lvg+KXVSAm//L4qnHKuW82ZQwVCwVoWy9Ffd9vehTwerrHduAuarRGZvm3UuamrBC2KP2CZ1kVwNG6rwVAwteYPYivHlR+I5damR5xGD1pibkn021V93UcPWXHQLhw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
